---
- name: Upload Snapshot Diagnostics
  hosts: all
  gather_facts: no
  roles:
    - batfish.base

  tasks:
  - name: Execute Batfish related tasks in a block that is "delegate_to -> localhost" and "run_once -> true"
    block:

    - name: Setup connection to Batfish service
      bf_session:
        host: "{{ batfish_server }}"
        name: remote_batfish

    - name: Collect diagnostics
      bf_upload_diagnostics:
        network: "{{ network }}"
        snapshot: "{{ snapshot }}"
        dry_run: "{{ dry_run|bool }}"
        contact_info: "{{ contact_info }}"
      register: diag_action

    - name: Print diagnostics action summary
      debug:
        var: diag_action.summary

    delegate_to: localhost
    run_once: true
